---
- hosts: localhost
  connection: local
  vars:
    serial: "{{ ansible_local.mac.serial }}"
    manifestURL: http://gorilla.qck.cm/manifest
    softwareURL: http://gorilla.qck.cm/
  tasks:
  - name: create directory for special ansible facts
    file: >
      state=directory
      path=/etc/ansible/facts.d
  - name: install special ansible facts
    file: >
      state=link
      src=/usr/local/gorilla/blackback/mac.fact
      dest=/etc/ansible/facts.d/mac.fact
  - name: install munki
    osx: >
      url=http://qck.cm/munkitools-2.2.4.2431.pkg
      creates=/usr/local/munki
      state=present
  - name: install munki preferences
    template: >
      src=ManagedInstalls.plist.j2
      dest=/Library/Preferences/ManagedInstalls.plist
      owner=root
      group=wheel
  - name: check in with gorilla
    shell: >
      /usr/local/gorilla/blackback/banana
  - name: run munki
    shell: >
      /usr/local/munki/managedsoftwareupdate -a && managedsoftwareupdate --installwithnologout
