#!/usr/bin/env python

import subprocess
import shlex
import urllib2
import json

result = subprocess.check_output(shlex.split("/etc/ansible/facts.d/mac.fact")).strip()

url = "http://chordata.qck.cm/i"

try:
    req = urllib2.Request(url, result, { 'Content-Type': 'application/json' })
    result = urllib2.urlopen(req)
except Exception, e:
    print str(e)
    exit(1)
